// pokemon
//     pokemon_id
//     move_1
//     move_2
//     individual_attack
//     individual_defense
//     individual_stamina
//     cp_multiplier
//     num_upgrades
//     additional_cp_multiplier
//     nickname
//     favorite
//     pokemon_display.gender
//     pokemon_display.shiny
// pokedex
//     pokemon_id
//     times_captured
//     captured_genders
//     captured_shiny
// player
//     level
//     pokemon_caught_by_type
// candies
//     family_id
//     candy